const {chromium}=require('../fly-bodies/node_modules/playwright');
const base=process.env.FLYLAB_PREVIEW_URL||'http://127.0.0.1:8770';
async function main(){const browser=await chromium.launch({headless:true,channel:'msedge',args:['--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&new URL(r.url()).origin===new URL(base).origin)errors.push('HTTP '+r.status()+' '+r.url());});
await page.goto(base+'/');for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('launcher overflow '+width);}
await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/fly-bodies/dist/?body=g1');await page.waitForFunction(()=>bodies?.bodyReady&&bodies?.brainReady,null,{timeout:45000});await page.locator('#pause').click();await page.locator('#profileWz').fill('0.3');await page.locator('#profileApply').click();if(await page.locator('#profileWz').inputValue()!=='.3'&&Number(await page.locator('#profileWz').inputValue())!==.3)throw Error('profile apply');await page.locator('[data-body=go1]').click();await page.waitForFunction(()=>bodies.body?.key==='go1'&&bodies.bodyReady&&!bodies.switching);if(Number(await page.locator('#profileWz').inputValue())!==1.5)throw Error('independent Go1 profile');await page.locator('[data-body=g1]').click();await page.waitForFunction(()=>bodies.body?.key==='g1'&&bodies.bodyReady&&!bodies.switching);if(Number(await page.locator('#profileWz').inputValue())!==.3)throw Error('G1 restore');await page.locator('#profileCandidate').click();await page.screenshot({path:'docs/implemented-bodies.png',fullPage:true});for(const width of [768,390,320]){await page.setViewportSize({width,height:900});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('bodies overflow '+width);}await page.screenshot({path:'docs/implemented-bodies-mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/fly-duck/dist/compare.html');await page.waitForFunction(()=>!document.getElementById('start').disabled,null,{timeout:45000});await page.locator('#start').click();await page.waitForFunction(()=>parseFloat(document.getElementById('clock').textContent)>=1,null,{timeout:45000});await page.locator('#pause').click();await page.waitForFunction(()=>!document.getElementById('reset-both').disabled);const first=await Promise.all(page.frames().slice(1).map(f=>f.evaluate(()=>({body:bodies.body.key,brain:bodies.brainKey,neurons:bodies.neurons,time:bodies.motion.time}))));if(first[0].body!=='duck'||first[1].body!=='duck'||first[0].time!==first[1].time||first[0].neurons===first[1].neurons)throw Error('comparison mismatch');await page.locator('#reset-both').click();await page.waitForFunction(()=>document.getElementById('clock').textContent.startsWith('0.0')&&!document.getElementById('reset-both').disabled);await page.locator('#show-brain').check();await page.screenshot({path:'docs/implemented-compare.png',fullPage:true});for(const width of [768,390,320]){await page.setViewportSize({width,height:900});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('compare overflow '+width);for(const f of page.frames().slice(1))if(await f.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('embed overflow '+width);}
await page.goto(base+'/fly-bodies/dist/?mode=compare&body=g1&brain=female');await page.waitForFunction(()=>bodies?.bodyReady&&bodies.brainReady,null,{timeout:45000});if(await page.evaluate(()=>bodies.body.key)!=='duck')throw Error('compare body escape');
await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/fly-walk/');await page.waitForFunction(()=>window.flywalk?.ready,null,{timeout:45000});await page.locator('#pause').click();const a=await page.evaluate(()=>({...flywalk.state}));await page.waitForTimeout(150);const b=await page.evaluate(()=>({...flywalk.state}));if(a.x!==b.x||a.y!==b.y)throw Error('walk pause');await page.screenshot({path:'docs/implemented-walk.png',fullPage:true});for(const width of [768,390,320]){await page.setViewportSize({width,height:900});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('walk overflow '+width);}console.log(JSON.stringify({responsiveWidths:[1440,768,390,320],profileIsolation:'pass',compareLock:'pass',compareFirstRun:first,compareReset:'pass',walkPause:'pass',errors},null,2));await browser.close();if(errors.length)process.exitCode=1;}
main().catch(e=>{console.error(e);process.exit(1);});

