import * as THREE from 'three';
export function setupWalkObservatory({state,lab,legs,scene,getActivity,getStimulus,setRate,singleStep,experiment}){
 const $=id=>document.getElementById(id);let selected=0,time=0,lastSample=-1,lastUI=0;const history=[];
 const names=['뒷다리','중간다리','앞다리'];
 const markers=legs.map(()=>{const marker=new THREE.Mesh(new THREE.CircleGeometry(.027,24),new THREE.MeshBasicMaterial({color:0x176b65,transparent:true,opacity:.7,depthWrite:false}));marker.rotation.x=-Math.PI/2;scene.add(marker);return marker;});
 const buttons=legs.map(({side,i},index)=>{const button=document.createElement('button');button.type='button';button.dataset.leg=index;button.innerHTML=`${side<0?'왼쪽':'오른쪽'} ${names[i]}<small>0.0° · 지지 구간</small>`;button.onclick=()=>{selected=index;};$('legMonitor').appendChild(button);return button;});
 $('playbackRate').onchange=e=>setRate(Number(e.target.value));$('singleStep').onclick=singleStep;
 for(const button of document.querySelectorAll('[data-experiment]'))button.onclick=()=>{const key=button.dataset.experiment;experiment(key);$('experimentNote').textContent=({target:'목표를 왼쪽에 놓았습니다. 무대에서 오른쪽으로 옮겨 회전 명령을 비교하세요.',antenna:'왼쪽 더듬이 입력을 제거했습니다. 냄새 막대와 목표 접근을 관찰하세요.',synapses:'시냅스 연결을 껐습니다. 감각 입력과 신경 발화·움직임의 차이를 관찰하세요.'})[key];};
 function sample(dt,previous){time+=dt;if(time-lastSample<.1)return;lastSample=time;history.push({time,speed:Math.hypot(state.x-previous.x,state.y-previous.y)/dt,turn:(state.yaw-previous.yaw)/dt,distance:state.banana?Math.hypot(state.banana.x-state.x,state.banana.y-state.y):null});while(history.length&&history[0].time<time-20)history.shift();}
 function graph(){const fields=['speed','turn','distance'],colors=['#245d8a','#a04c27','#176b65'];let content='';fields.forEach((field,index)=>{const top=8+index*44,values=history.filter(p=>p[field]!=null),max=Math.max(field==='turn'?.5:1,...values.map(p=>Math.abs(p[field])));content+=`<line x1="8" y1="${top+35}" x2="632" y2="${top+35}" stroke="#d6dfe5"/><text x="12" y="${top+10}" fill="${colors[index]}" font-size="10">${['속도','회전','거리'][index]} · ±${max.toFixed(1)}</text>`;let path='',connected=false;for(const p of history){if(p[field]==null){connected=false;continue;}const x=8+(p.time-Math.max(0,time-20))/20*624,y=top+22-p[field]/max*16;path+=`${connected?'L':'M'}${x.toFixed(1)},${y.toFixed(1)} `;connected=true;}content+=`<path d="${path}" fill="none" stroke="${colors[index]}" stroke-width="1.8"/>`;});$('motionChart').innerHTML=content;}
 function update(){legs.forEach(({group,side,i},index)=>{const phase=state.legPhase[side<0?0:1]+(i%2===0?0:Math.PI)+(side<0?Math.PI:0),lift=Math.sin(phase)>0;group.traverse(object=>{if(object.material?.color)object.material.color.setHex(index===selected?0x245d8a:0x3d2f20);});const point=group.localToWorld(new THREE.Vector3(side*.18,-.28,0));markers[index].position.set(point.x,.008,point.z);markers[index].visible=$('showFeet').checked;markers[index].material.color.setHex(lift?0xa04c27:0x176b65);buttons[index].setAttribute('aria-pressed',String(index===selected));buttons[index].querySelector('small').textContent=`${THREE.MathUtils.radToDeg(group.rotation.y).toFixed(1)}° · ${lift?'들림':'지지'} 구간`;});
  const chosen=legs[selected];$('legDetail').textContent=`선택: ${chosen.side<0?'왼쪽':'오른쪽'} ${names[chosen.i]} · 다리 뿌리 회전각 / 초록: 지지 구간, 주황: 들림 구간 (애니메이션 추정)`;
  const now=performance.now();if(now-lastUI<100)return;lastUI=now;const a=getActivity()||{};const input=getStimulus(),left=input.olfactory_left,right=input.olfactory_right;
  $('flowInput').textContent=`${left.toFixed(2)} / ${right.toFixed(2)}`;$('smellL').value=left;$('smellR').value=right;const percent=value=>(100*(value||0)).toFixed(2)+'%';$('flowAL').textContent=`${percent(a.scentLeft)} / ${percent(a.scentRight)}`;$('flowDN').textContent=`${percent(a.left)} / ${percent(a.right)}`;$('flowCommand').textContent=`${(a.command?.forward||0).toFixed(2)} 단위/s / ${(a.command?.turn||0).toFixed(2)} rad/s`;graph();const last=history.at(-1);$('chartReadout').textContent=last?`관찰 시간 ${time.toFixed(1)}초 · 이동 속도 ${last.speed.toFixed(2)} · 회전 ${last.turn.toFixed(2)} · 목표 거리 ${last.distance==null?'목표 없음':last.distance.toFixed(2)} · 각 선은 독립 눈금`: '실행하면 기록을 시작합니다. 각 선은 독립 눈금입니다.';
 }
 function reset(){history.length=0;time=0;lastSample=-1;selected=0;$('experimentNote').textContent='정상 더듬이와 연결된 시냅스로 초기화했습니다.';}
 return {sample,update,reset};
}
